#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May  6 20:31:17 2019

@author: sh.elisaveta

"""


import bs4
import requests

h = requests.get('https://leroymerlin.ru/catalogue/kraski-dlya-sten-i-potolkov/?display=90')
with open('test.html', 'w', encoding='utf-8') as file_name:
	file_name.write(h.text)

soup = bs4.BeautifulSoup(h.text, features="html.parser")
#a = soup.find_all("div", {"data-product-name = " : ""})

b = soup.find_all(attrs={"data-product-name": True})
for i in b:
	print(i['data-product-id'], i['data-product-name'])
#print(b)